/*
 * GoT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"github.com/gorilla/mux"
	"net/http"
	"strings"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Welcome to the Project#1|REST\nProgrammers:\n-Allen Segura\n-Jonathan Vindas")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"BattleBattleIdDelete",
		strings.ToUpper("Delete"),
		"/battle/{battleId}",
		BattleBattleIdDelete,
	},

	Route{
		"BattleBattleIdGet",
		strings.ToUpper("Get"),
		"/battle/{battleId}",
		BattleBattleIdGet,
	},

	Route{
		"BattleBattleIdPut",
		strings.ToUpper("Put"),
		"/battle/{battleId}",
		BattleBattleIdPut,
	},

	Route{
		"BattlePost",
		strings.ToUpper("Post"),
		"/battle/",
		BattlePost,
	},

	Route{
		"CharacterCharacterIdDelete",
		strings.ToUpper("Delete"),
		"/character/{characterId}",
		CharacterCharacterIdDelete,
	},

	Route{
		"CharacterCharacterIdGet",
		strings.ToUpper("Get"),
		"/character/{characterId}",
		CharacterCharacterIdGet,
	},

	Route{
		"CharacterCharacterIdPut",
		strings.ToUpper("Put"),
		"/character/{characterId}",
		CharacterCharacterIdPut,
	},

	Route{
		"CharacterPost",
		strings.ToUpper("Post"),
		"/character/",
		CharacterPost,
	},

	Route{
		"HouseHouseIdDelete",
		strings.ToUpper("Delete"),
		"/house/{houseId}",
		HouseHouseIdDelete,
	},

	Route{
		"HouseHouseIdGet",
		strings.ToUpper("Get"),
		"/house/{houseId}",
		HouseHouseIdGet,
	},

	Route{
		"HouseHouseIdPut",
		strings.ToUpper("Put"),
		"/house/{houseId}",
		HouseHouseIdPut,
	},

	Route{
		"HouseHouseNameBattlePost",
		strings.ToUpper("Post"),
		"/house/{houseName}/battle/",
		HouseHouseNameBattlePost,
	},

	Route{
		"HousePost",
		strings.ToUpper("Post"),
		"/house/",
		HousePost,
	},

	Route{
		"HouseHouseIdBattleGet",
		strings.ToUpper("Get"),
		"/house/{houseId}/battle/",
		HouseHouseIdBattleGet,
	},

	Route{
		"HouseHouseIdCharacterGet",
		strings.ToUpper("Get"),
		"/house/{houseId}/character/",
		HouseHouseIdCharacterGet,
	},

	Route{
		"HouseHouseNameBattleLocationDelete",
		strings.ToUpper("Delete"),
		"/house/{houseName}/battle/{location}",
		HouseHouseNameBattleLocationDelete,
	},

	Route{
		"HouseHouseIdBattleBattleNameGet",
		strings.ToUpper("Get"),
		"/house/{houseId}/battle/{battleName}",
		HouseHouseIdBattleBattleNameGet,
	},

	Route{
		"HouseHouseIdCharacterCharacterNameGet",
		strings.ToUpper("Get"),
		"/house/{houseId}/character/{characterName}",
		HouseHouseIdCharacterCharacterNameGet,
	},

	Route{
		"HouseHouseNameCharacterPost",
		strings.ToUpper("Post"),
		"/house/{houseName}/character/",
		HouseHouseNameCharacterPost,
	},
}
