/*
 * GoT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Battle struct {
     BattleId         string `json:"battleId"`
     BattleName       string `json:"battleName"`
     AttackerKing     string `json:"attackerKing"`
     Defenderking     string `json:"defenderking"`
     AttackerHouse    string `json:"attackerHouse"`
     ParticipateHouse string `json:"defenderHouse"`
     BattleType       string `json:"battleType"`
     Year             string `json:"year"`
     Location         string `json:"location"`
     Region           string `json:"region"`
}
