/*
 * GoT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Character struct {
     CharacterId   string `json:"characterId,omitempty"`
     Name          string `json:"name,omitempty"`
     Title         string `json:"title,omitempty"`
     Male          string `json:"male,omitempty"`
     Culture       string `json:"culture,omitempty"`
     Mother        string `json:"mother,omitempty"`
     Father        string `json:"father,omitempty"`
     House         string `json:"house,omitempty"`
     Age           string `json:"age,omitempty"`
}
