/*
 * GoT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type House struct {
	  HouseId       string `json:"houseId,omitempty"`
	  CharacterName string `json:"characterName,omitempty"`
		Location      string `json:"location,omitempty"`
	  HouseName     string `json:"houseName,omitempty"`
	  DeathYear     string `json:"deathYear,omitempty"`
	  BookOfDeath   string `json:"bookOfDeath,omitempty"`
	  Gender        string `json:"gender,omitempty"`
	  Nobility      string `json:"nobility,omitempty"`
	  Battle        []Battle `json:"battle,omitempty"`
	  Character     []Character `json:"character,omitempty"`
}
